### ISSUE TITLE
Expand/collapse metastases, image number confusing, Model Details sort

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#14]
I was looking at a Model details page and was testing the expand all, collapse all buttons and saw that while they worked for Pathology notes, they did not work for metastases.-Debbie also reported this.

In the second row of this search results the notes say 3 pathology images but if you go to the model details you only see one, http://bhmtbdb01:8080/mtbwi2/tumorSummary.do?strainKey=62&organOfOriginKey=5&tumorFrequencyKeys=129,131,17128,25494,25495,25498,25499. This is due to two images being in the metastases. They are on the page, they just don’t show if you do not expand the metastases. That is likely what we want but it still could be confusing.

 

Lastly a question, what is the default sort value for the Model details? It is not sex, frequency, age of detection, reference date or author name. I thought it was frequency but I am obviously wrong. All the sort buttons work except that for frequency very high and observed intermingle after the sort.

**Comment by ahcurrier** [comment]
Hi @DABegley — the expand/collapse issue (12) is now resolved. You're right that the image count is not clear — what's the consensus: leave as-is or change? As for sort order, it's now updated to default to sex.

On frequency sorting, this is likely because there is no numeric data associated with 'observed' and 'very high'. @sneuhaus — would you be able to expose a numeric value for frequency here?:
https://github.com/mgijax/mtb-dao/blob/9e8c056dd154c95237258207f4af535a85842ab6/src/org/jax/mgi/mtb/dao/custom/mtb/MTBTumorFrequencySummaryDTO.java

**Comment by ahcurrier** [comment]
Resolved here:
https://github.com/mgijax/mtb-wi/commit/76e3a106e8d1a4517a5fb6857b894ae78b5e5d2d
