### ISSUE TITLE
Update pdxDetails.jsp

### ISSUE THREAD

**Issue by ahcurrier** [mgijax/mtb-wi#33]

**Comment by sneuhaus** [comment]
This page allows for editing data for PDX models, that is only available internally on the dev site.
Converting the editing functionality can be done at a later date.

**Comment by ahcurrier** [comment]
Ready for review. E.g.:
http://bhmtbdb01:8080/mtbwi2/pdxDetails.do?modelID=TM01087

**Comment by CarolBult** [comment]
@ahcurrier 
I did a few searches...it appears to be working. 
But:
1) the font sizes are teeny 
2) the spacing of the fields needs to be changed so that the same information is presented in a more compact format (compare to what is live right now for field layout)
3) in the search results, the listing of all the matching models needs to be more compact (see the current search results page)
4) the summary of the search parameters takes up too much of the page and is not labeled (something like "You searched for....")
5) There are a few munged words and tool tips (see attached power point)
[PDXSearch.pptx](https://github.com/mgijax/mtb-wi/files/4926205/PDXSearch.pptx)
